### ISSUE TITLE
Package in to CLI

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/meteor-launch#1]
We should package this functionality in to a CLI to make it easier to use. Ex:

~~~
launch hockey example.com
~~~

Also, initializing should be made a lot easier. We need a command like this to start a new project:

~~~
launch init
~~~

Then, `launch` should read the settings out of some kind `.launch` file, instead of using environment variables for everything.

This should eliminate the need to have the `launch` file and all the `fastlane` files sitting in your repo. Just a settings file.

**Comment by johnthepink** [comment]
@jbaxleyiii thoughts?

**Comment by jbaxleyiii** [comment]
@johnthepink I think thats a great idea. What language do you want to use? This project requires both ruby and node so we could do either or write it in something else. Maybe plain shell scripts or even Go for a super fun time.

If we do use ruby I would recommend [commander](https://github.com/tj/commander).
If we use node I would go with [vorpal](https://github.com/dthree/vorpal) (is new and looks cool) or [liftoff](https://github.com/js-cli/js-liftoff) which is what Norma 1.0 is written with.

For the file API, I would say go with a `.launch` file like you mentioned or maybe a `Launch` file. No ext as to not mess with other programs. I would probably recommend `.launch` to hold needed scripts and files and `Launch` as the file for configuration. `Launch` is tracked, `.launch` is not.

Thoughts?

**Comment by jbaxleyiii** [comment]
@johnthepink what kind of file api are you thinking of?

Language wise, If you want we could use HCL using [this](https://github.com/NewSpring/node-hcl) package. It is pretty far a long, or we can stick with JSON, or even YAML

**Comment by johnthepink** [comment]
@jbaxleyiii I think it should definitely be a Node app, since it's directed at making meteor builds and deploys easier. Writing it in Ruby would be fun, but could isolate the community it's intended for. I'll check out vorpal.

And I like the idea of using HCL. It will make separating out all the different tasks easier to manage. Good call.

![](http://i.giphy.com/AaosjRHKjEcXm.gif)

**Comment by jbaxleyiii** [comment]
:+1:, you can also take a look at the 2.0 branch of Norma in the cli folder. I dropped using a third party library since its mainly parsing arguments and is pretty easy with minimist https://github.com/NewSpring/Norma/blob/2.0/cli/norma.js

**Comment by johnthepink** [comment]
Closed via #6
