### ISSUE TITLE
Launch init crashes on installing fastlane

### ISSUE THREAD

**Issue by wesleyfsmith** [NewSpring/meteor-launch#103]
When I run _launch init_ the command immediately crashes with the following output:

```
Installing fastlane...
undefined is not a function
```

**Comment by johnthepink** [comment]
Thanks for reporting. I'll investigate. 

For now, you should be able to get past this by installing fastlane before. 

~~~
gem install fastlane 
~~~

**Comment by johnthepink** [comment]
@wesleyfsmith I wasn't able to replicate this issue on a new project. What version of launch are you running? I filed an issue to make this easier in the future #104, but you should be able to do this as well:

```
npm list -g meteor-launch
```

Some other things that may be useful:

1. node version `node -v`
2. ruby version `ruby -v`

Thanks!

**Comment by wesleyfsmith** [comment]
@johnthepink, thank you for the quick reply. I was able to install the fastlane gem but it doesn't seem to have made any difference, it still says "Installing fastlane... undefined is not a function" and crashes.

Here are the versions I'm using
```
meteor-launch@0.3.2
node v0.10.28
ruby 2.0.0p648
```

I appreciate the help, I'd really like to use this tool.

**Comment by wesleyfsmith** [comment]
How can I get a more descriptive stack trace so I can figure out what line it's breaking on? I know how to do that with other packages but with this package I'm less certain. Thanks!

**Comment by johnthepink** [comment]
@wesleyfsmith thanks for the info. So that is the latest version of launch, but I'm betting it has something to do with node 0.10. We are currently only testing launch on node 4, 5, and 6. 

https://travis-ci.org/NewSpring/meteor-launch

Is there a specific reason you are using node 0.10? If so, I can look in to supporting it in the future. But if not, I'd definitely recommend upgrading to at least node 6. Node 7 is out now as well, but 6 is LTS.

**Comment by wesleyfsmith** [comment]
@johnthepink Upgrading my node fixed the issue. I forgot that meteor has it's own version of node self-contained and that my global version of node was old. Thanks for helping! Looking forward to using the project.

**Comment by johnthepink** [comment]
No problem. Thanks for checking it out. Let me know how it goes, or if
there is anything you'd like to see added!
