### ISSUE TITLE
Forcing me to set slack_url ?

### ISSUE THREAD

**Issue by wesleyfsmith** [NewSpring/meteor-launch#106]
I'm trying to run

```
launch hockey
```

After getting the iOS build set up. However, the script keeps trying to force me to input a slack_url, which I don't have, so I eventually have to put in a bogus url and then it errors out and crashes. How can I disable the slack integration? Putting it in launch.json as an empty string doesn't seem to work either. Thanks!

**Comment by johnthepink** [comment]
What's the error you are getting? I don't have a slack url set on this example project https://github.com/NewSpring/launch-basic-example, and the builds have seemed okay https://travis-ci.org/NewSpring/launch-basic-example/builds

I'll do some investigating.

**Comment by johnthepink** [comment]
I was able to replicate. Should have a fix in a few.

**Comment by johnthepink** [comment]
@wesleyfsmith I just released 0.3.3, see if that fixes the issue for you. I think one of the dependencies updated.

**Comment by wesleyfsmith** [comment]
Awesome, thanks! Fixed the issue.
