### ISSUE TITLE
Error: Connection reset by peer - SSL_connect

### ISSUE THREAD

**Issue by wesleyfsmith** [NewSpring/meteor-launch#108]
I am getting the following error why trying to push to hockey or testflight:

```
[11:15:06]: Starting login with user 'wesleyfsmith@gmail.com'
[11:15:19]: Variable Dump:
[11:15:19]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios hockey"}
[11:15:19]: Connection reset by peer - SSL_connect
```

I'm assuming something is wrong with my certs / credentials, but I cannot figure it out. I followed the link in the guide for generated a certificate, but I did not set a password on the cert as per the instructions [here](https://calvium.com/how-to-make-a-p12-file/). I've tried not setting a password for "CERT_PASSWORD" in launch.json, as well as setting a password and neither have worked. The rest of my login information is correct as far as I can tell (that is, it works fine to log in to the developer portal through the web).

Would love some direction @johnthepink. Thanks for your help so far!

**Comment by johnthepink** [comment]
I'll take a look at this tonight. Thanks!

**Comment by wesleyfsmith** [comment]
The issue is definately related to [this](https://github.com/fastlane/fastlane/issues/6553).

However, I've spent the entire day so far and made no progress at all on fixing the issue. I even nuked my ruby, my gems, and reinstalled everything from scratch but it still throws the ssl error.

**Comment by wesleyfsmith** [comment]
Fixed it. It was some insane ruby version with fastlane SSL thing. Not really sure exactly which step fixed it, but it's not throwing the SSL error anymore. Thanks!
