### ISSUE TITLE
Error: Opening Xcode :( ... undefined

### ISSUE THREAD

**Issue by wesleyfsmith** [NewSpring/meteor-launch#109]
When trying to build for ios, I get the following error:

```
Opening Xcode :( ...                          
undefined
```

Then, Xcode opens up, and I'm presented with the following dialog:

```
The workspace file at “/Users/wesley/Projects/oji/.build/ios/project/oji.xcodeproj/project.xcworkspace” has been modified by another application.

Do you want to keep the Xcode version, or revert to the version on disk?
```

Would love any hints on where to look to solve this. Thanks so much!

**Comment by johnthepink** [comment]
@wesleyfsmith Unfortunately, this is intended functionality. The Xcode project has to be opened to ensure a couple things get created. Or, at least at the time of building this that was the case. 

The undefined is just coming from a `console.log` that I need to remove.

The message you got inside Xcode I've generally seen when an Xcode project is open, and then run a launch build, which replaces the open file and causes the message.

**Comment by wesleyfsmith** [comment]
@johnthepink Are you saying that the build is completely correctly then? I guess I've been struggling so much to get everything running that I just assumed it was erroring out :-)

**Comment by johnthepink** [comment]
@wesleyfsmith yep that sounds correct to me! Thanks for sticking with it. Let me know how we can improve :)
