### ISSUE TITLE
launch testflight doesn't replace build

### ISSUE THREAD

**Issue by wesleyfsmith** [NewSpring/meteor-launch#113]
I noticed that when I run _launch testflight_ the build doesn't actually seem to get updated. I'm not sure if it's only the version file, or the entire folder, but when I tried to push to itunes connect it errored out saying that a build with that version number had already been submitted, even though that was the old version number and not the number I was using in the build I just generated.

To fix, I deleted the entire .build directory from my project, then re-built and submitted and it uploaded the newer version as expected. Perhaps the easy fix is to rm the entire build folder upon rebuilding?

**Comment by johnthepink** [comment]
Ah yes. `launch testflight` does just try to take whatever is in `.build` and upload it. You would need to do another `launch build`, having updated the `mobile-config.json`, before trying to push to testflight again.

Or, if you want to upload the same build, you could open the xcode project and change the build number.

**Comment by wesleyfsmith** [comment]
So actually, this is happening even after re-running `launch build`. And deleting the folder and then running `launch build`. Usually after trying 2-4 times it accepts the new version number and then goes through.

**Comment by johnthepink** [comment]
Interesting. I would imagine that's a problem with meteor's build tool then.

I have noticed issues with Android builds that use Crosswalk before:

https://github.com/NewSpring/meteor-launch/issues/102

...but I haven't had that issue with iOS. I will try to reproduce, but if you have some concrete reproduction steps please let me know.

**Comment by wesleyfsmith** [comment]
I wish I had better steps for you, all I've done is

- bump version number
- run `launch build`
- run `launch testflight`
- If it complains and says I haven't bumped the version number, I just repeat the last two steps until it eventually accepts it.

I'll see if I can do more digging to give you more information. It could be on my end if you can't reproduce, but I'm using the newest version of meteor with all the patches.

**Comment by johnthepink** [comment]
@jbaxleyiii does this look similar to the issue you were having?

**Comment by jbaxleyiii** [comment]
Yep! I had to clear out my .build folder each time

**Comment by johnthepink** [comment]
@jbaxleyiii @wesleyfsmith cool. This is most likely an issue with the meteor build tool. What do you guys think about having launch clear the build folder for you?

**Comment by jbaxleyiii** [comment]
Sounds like a great way to ensure clean builds

**Comment by johnthepink** [comment]
It's not ideal, as it does slow down the build process. But, seems like the only reliable way for now.

**Comment by wesleyfsmith** [comment]
@johnthepink I'm fine with having the build cleared out, even it slows things down. Better for it to work correctly than guess if my build is up to date.

**Comment by johnthepink** [comment]
@wesleyfsmith @jbaxleyiii Fixed in 0.3.4
