### ISSUE TITLE
Testflight failing with update, code signing error

### ISSUE THREAD

**Issue by wesleyfsmith** [NewSpring/meteor-launch#123]
After updating to the newest fastlane, sigh, gym, and meteor-launch I can no longer push my app up to testflight, which was working previously. Here's the error that I'm getting:

```
Provisioning profile "com.oji AdHoc 1480555445" doesn't include signing certificate "iPhone Distribution: Wesley Smith (7RX8A9CM44)".

Code signing is required for product type 'Application' in SDK 'iOS 10.1'
```

I realize this may be a fastlane issue, and not so much a meteor-launch issue, but it's strange to me that it was working great, and now I'm getting this error suddenly. To my knowledge I haven't changed my certificates are done anything like that.

**Comment by wesleyfsmith** [comment]
Deleted an extra iPhone Distribution certificate from my keychain and it fixed the issue. Not really sure why...

**Comment by johnthepink** [comment]
Nice! Good to know.
