### ISSUE TITLE
How to build to custom mobile server?

### ISSUE THREAD

**Issue by learningdesignlabs** [NewSpring/meteor-launch#125]
How might one specify a custom server for the mobile app to connect to for DDP requests (instead of Galaxy) when running the "build" command?

**Comment by learningdesignlabs** [comment]
Looks like I missed the  "myapp.com" part in the following sample from the docs, just in case it helps anyone to highlight it here:
launch build myapp.com path/to/optional/settings.json

**Comment by johnthepink** [comment]
@learningdesignlabs thanks for checking out the project. Let me know how it goes for you :)
