### ISSUE TITLE
Can't install NPM

### ISSUE THREAD

**Issue by 88plug** [NewSpring/meteor-launch#27]
npm install -g meteor-launch
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node5/5.11.0/bin/node" "/usr/local/bin/npm" "install" "-g" "meteor-launch"
npm ERR! node v5.11.0
npm ERR! npm  v3.9.5
npm ERR! path /usr/local/lib/node_modules/meteor-launch/lib/index.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/meteor-launch/lib/index.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/meteor-launch/lib/index.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:

**Comment by johnthepink** [comment]
Hey @88plug sorry about that! I did a bad publish on version 0.2.4. I just published 0.2.5 which should fix the issue for you. Let me know how it goes!

**Comment by 88plug** [comment]
Bingo!
