### ISSUE TITLE
Can't install fastlane

### ISSUE THREAD

**Issue by 88plug** [NewSpring/meteor-launch#29]
launch init
Installing fastlane...
ERROR:  Error installing fastlane:
	"snapshot" from snapshot conflicts with /usr/local/bin/snapshot
Command failed: sudo gem install fastlane
ERROR:  Error installing fastlane:
	"snapshot" from snapshot conflicts with /usr/local/bin/snapshot

**Comment by johnthepink** [comment]
@88plug are you using RVM? Or system Ruby?

**Comment by 88plug** [comment]
I am on os x - not using anything special

**Comment by 88plug** [comment]
pretty sure I don't have ruby installed - do I need it?

**Comment by johnthepink** [comment]
Ruby comes pre-installed on OSX. So just running `ruby -v` should give you a version.

I do need to handle that case better. Right now on `launch init`, it will try to install fastlane, like you see. But, if it already finds fastlane, then it will skip over it.

Try running `sudo gem install fastlane`, or just `gem install fastlane` and see if either of those work? If so, you should be able run `launch init` just fine.

Sorry you're having so many issues. Thanks for being patient! :)

**Comment by 88plug** [comment]
ruby -v
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]

ran sudo gem install fastlane
asked me to overwrite snapshot I said yes
snapshot's executable "snapshot" conflicts with /usr/local/bin/snapshot
Overwrite the executable? [yN]  y

then
launch init
launch.json created. Open it and fill out the vars
 
Thanks for the responsiveness!

**Comment by johnthepink** [comment]
Awesome! Let me know if you have any questions or need any help. I'm happy to help out.
