### ISSUE TITLE
explore hcl

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/meteor-launch#4]

**Comment by jbaxleyiii** [comment]
:+1:

**Comment by johnthepink** [comment]
At this point, I am leaning towards sticking the with `launch.json` file for now. But, I'm still open to suggestions.

Maybe we can support both in a future release. What I don't want to do is confuse the difference between the launch file variables and environment variables. That way, it's easy to understand how to override the variables, for instance on a CI.
