### ISSUE TITLE
build path or source in launch.json

### ISSUE THREAD

**Issue by mike623** [NewSpring/meteor-launch#79]
I think is good to have these setting to change source path or output path e.g
````
{
	source: "./app",
	buildPath: "./build"
}
````

**Comment by johnthepink** [comment]
@mike623 thanks for the feedback! I think the settings you are talking about are duplicates of issues #49 and #30.

Is this a blocking issue for you right now?

**Comment by mike623** [comment]
@johnthepink , well. I think `output_path` is more important now

**Comment by johnthepink** [comment]
@mike623 good to know. I will prioritize that when I get a chance. I'll close this issue for now in favor of the other two. 

Feel free to jump in if you want to send a PR! Just make a comment on the issue

**Comment by johnthepink** [comment]
@mike623 just published `0.3.0` which has support for a custom source path and build path. Let me know if that works for you!
